### ISSUE TITLE
Backup feeds

### ISSUE THREAD

**Issue by Mr-Iashog** [BS-Harou/Smart-RSS#32]
Hi, how could I **backup** al my folders and feeds in the smart rss? Nowadays, reorder the icons in the Opera toolbar demands reinstalling them in proper order. Congratulations for the extension, I sendo you my Best regards, Mr-I.

**Comment by martinkadlec0** [comment]
In settings of the extensions you can either export OPML (only feeds) or SMART (feeds + articles). I recommend exporting both as the SMART is sometimes too bug and might fail.

btw, this extensions is not under development for some time now and unless someone takes over there probably won't by any future updates.
